name: 10 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build and Test Java App
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Build the project (skip tests only during packaging)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy build artifact
        run: |
          mkdir -p candidate-binary
          cp target/*.jar candidate-binary/

      # Run unit tests
      - name: Test with Maven
        run: mvn test

      # Collect test results
      - name: Copy test result files
        run: |
          mkdir -p test-results
          if [ -d "target/surefire-reports" ]; then
            cp target/surefire-reports/TEST-*.xml test-results || echo "No test result files found"
          else
            echo "No test result folder found"
          fi

      # Upload build artifact
      - name: Upload Application Binary
        uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: candidate-binary

      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: test-results

      # Publish test results in GitHub UI
      - name: Publish Unit Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          junit_files: "test-results/**/*.xml"
