name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test Java App
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sca:
    name: Software Composition Analysis (SCA)
    needs: build
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  sast:
    name: Static Application Security Testing (SAST)
    needs: build
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  license-compliance:
    name: License Compliance Check
    needs: build
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit

  docker:
    name: Build Docker Image
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  container-image-scan:
    name: Scan Docker Image for Vulnerabilities
    needs: docker
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}

  dast:
    name: Dynamic Application Security Testing (DAST)
    needs: [build, docker]
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
